name: build

on:
  push:
    branches: 
      - master
    paths:
      - 'app/**'
      - '.github/workflows/app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add remote origin
      run: git remote add heroku https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
    - name: Deploy to Heroku
      run: git push heroku `git subtree split --prefix app master`:refs/heads/master --force
